- config/phobos.yml.example
- lib/phobos/executor.rb
- lib/phobos/listener.rb
- spec/lib/phobos/executor_spec.rb
- spec/lib/phobos/listener_spec.rb
Apart from adding [the configuration options](https://github.com/zendesk/ruby-kafka/blob/9bb557efe545ab393b2143ac9c8a96dc7539b2e2/lib/kafka/consumer.rb#L213) from ruby-kafka, this change speeds up the test run 2x by not waiting for 5 seconds every time a listener is shut down in the tests.
> Allow configuring consumer's min_bytes and max_wait_time

- CHANGELOG.md
- README.md
- lib/phobos.rb
- lib/phobos/version.rb
- spec/fixtures/phobos_config.yml.erb
- spec/lib/phobos_spec.rb
Adds the possibility to have ERB syntax in the config file so that you can inject parameters
like:
```yml
logger:
file: log/phobos.log
kafka:
client_id: <%='InjectedThroughERB'%>
```
> Add support for erb syntax in phobos config file

- README.md
- lib/phobos.rb
- spec/lib/phobos_spec.rb
Hello! I would like to propose an option to import settings to Phobos from a Hash-like object.
Why?
I've already have a settings managing mechanism in place (https://github.com/railsconfig/config). 
It takes care about settings inheritance and supports several environments. 
I would like to reuse my current configuration setup without adding extra `phobos.yml` files for every environment.
This PR adds an option to provide a hash to `Phobos.configure` method.
> Add support for hash provided settings

- README.md
- lib/phobos.rb
- lib/phobos/cli.rb
- lib/phobos/cli/start.rb
- spec/fixtures/extra_listeners.yml
- spec/lib/phobos/cli/start_spec.rb
- spec/lib/phobos/cli_spec.rb
- spec/lib/phobos_spec.rb
- Allows loading config from a file during startup to be disabled, useful if you prefer to configure phobos with a hash in ruby instead of with a yaml file.
- Allows a separate listeners file to be specified, making it easy to run multiple phobos processes with different sets of listeners.
> Make configuration, especially of listeners, more flexible.

- config/phobos.yml.example
- lib/phobos.rb
- spec/lib/phobos/cli_spec.rb
- spec/lib/phobos_spec.rb
- spec/support/cli_helpers.rb
When running a phobos project inside a docker container, it would be nice to capture stdout as json, so splunk has a good time parsing the phobos logs.
> Add support for formatting log for stdout as json

- CHANGELOG.md
- config/phobos.yml.example
- lib/phobos/actions/process_batch.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/cli/start.rb
- lib/phobos/executor.rb
- lib/phobos/listener.rb
- spec/fixtures/batch_listener.yml
- spec/fixtures/invalid_delivery_listener.yml
- spec/fixtures/message_listener.yml
- spec/fixtures/no_delivery_option.yml
- spec/lib/phobos/actions/process_batch_spec.rb
- spec/lib/phobos/actions/process_message_spec.rb
- spec/lib/phobos/cli/start_spec.rb
- spec/lib/phobos/listener_spec.rb
Addressing https://github.com/klarna/phobos/issues/21
I found that in production that I need to process using `each_message` for certain listeners. This PR adds that ability via the `consume_in_batches` listener option. I had to move some code around to accomplish this, but I think everything looks good.
A couple
1.) I added specs, but let me know if they are sufficient enough.
2.) I'm open to any configuration / naming changes
> Add each_message support

- lib/phobos/cli.rb
- phobos.gemspec
Hi,
I was able to run this locally with ruby 2.3.4 and Rails 3.0.5.
Had to modify the CLI to use `method_option`, because `option` wasn't working.
Let me know if you need anything else.
Thanks
> Change activesupport dependency from 4 to 3

- CHANGELOG.md
- README.md
- lib/phobos/actions/process_batch.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/instrumentation.rb
- lib/phobos/listener.rb
- spec/lib/phobos/listener_spec.rb
Add `handler` to the instrumentation payload for listener events.
Remove `time_elapsed` (seconds) in instrumentation payload, in favor of using the `duration` (ms) method on the active support instrumentation event instead. This simplifies our code a bit.
> Instrument handlers

- lib/phobos/listener.rb
See https://github.com/klarna/phobos/issues/44
Change `DEFAULT_MAX_BYTES_PER_PARTITION` to match the `ruby-kafka` default. https://github.com/zendesk/ruby-kafka/blob/84986d08bf2c27af006fb3006ec0f0b4e89b91b2/lib/kafka/consumer.rb#L91
The new value will be around 1MB, which is the same size as the default broker configuration value of `max.message.bytes`.
> Change default max bytes per partition to 1 MB

- .travis.yml
Many deployments are still on "older" rubies. This ensures that both officially supported versions are working.
> Ruby 2.3 support

- config/phobos.yml.example
- lib/phobos/listener.rb
`ruby-kafka` exposes offset retention time setting to the consumer API. This setting allows a custom offset retention time period per kafka consumer group.
From the `ruby-kafka` README
> Stale offsets are periodically purged by the broker. The broker setting offsets.retention.minutes controls the retention window for committed offsets, and defaults to 1 day. The length of the retention window, known as offset retention time, can be changed for the consumer.
See: https://github.com/zendesk/ruby-kafka/pull/316
> Add offset_retention_time to consumer options

- lib/phobos.rb
Do not set `ENV['RAILS_ENV']` or `ENV['RACK_ENV']` (see [lib/phobos.rb#L34](https://github.com/klarna/phobos/blob/v1.7.0/lib/phobos.rb#L34)).  It appears this is only used for logging purposes, and if `ENV['RAILS_ENV']` is set but `ENV['RACK_ENV']` is unset it results in `ENV['RAILS_ENV']` being set to `'development'`.  Neither of these should be set by this library.
> Phobos overwrites ENV['RAILS_ENV'] with incorrect value.

- config/phobos.yml.example
- lib/phobos/executor.rb
- lib/phobos/listener.rb
- spec/lib/phobos/listener_spec.rb
Provides the ability to override `session_timeout`, `heartbeat_interval`, `offset_retention_time`, `offset_commit_interval`, and `offset_commit_threshold` per listener.
For example, it might be desirable to relax the `offset_commit_interval` / `offset_commit_threshold` for listeners that are idempotent.
> Allow listeners to overwrite consumer opts

- CHANGELOG.md
- README.md
- lib/phobos.rb
- spec/lib/phobos_spec.rb
I have a custom Rails logger I'm using which uses ActiveSupport tagged logging and not the `Logging` framework. This PR allows me to set the custom logger to Phobos instead of being required to use Logging.
> Allow a custom logger for both Phobos and RubyKafka.

- CHANGELOG.md
- lib/phobos/actions/process_message.rb
- lib/phobos/listener.rb
- spec/lib/phobos/actions/process_message_spec.rb
Also, break down big retry backoff into smaller sleep intervals, in
order to send heartbeat in time and faster detection of listerner
stop.
> Send heartbeat while retrying on processing errors

- README.md
- lib/phobos.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/handler.rb
- spec/lib/phobos/actions/process_message_spec.rb
- spec/lib/phobos/handler_spec.rb
- spec/lib/phobos/test/helper_spec.rb
1) **Consistency/readability**: It's generally confusing that `#before_consume` is an instance method on the handler and `.around_consume` is a class method. 
2) **Flexibility**: Allows users to set custom instance variables on the handler that will be accessible in around_consume.
This feature has come up consistently during development. For example, we have built some custom logic into around_consume that relies on metadata from the original payload. We lose that metadata in the before_consume step, forcing us to put all of the logic into around_consume. Another example is error handling for before_consume. In some cases we want to catch exceptions in before_consume and continue to proceed with message processing. Setting an instance variable on the handler is a logical way to signal …
> Around consume instance method

- CHANGELOG.md
- lib/phobos/producer.rb
- spec/lib/phobos/producer_spec.rb
Currently, Phobos only uses message/payload keys. It automatically sets the partition key to be the same as the payload key.
There are use cases where these should be separate. For example, say there is a comment on a post. The Comments topic would want the comment ID to be the payload key (since it indicates that all updates to that individual comment should be compacted) while the partition key would likely be the post (so all actions related to the same post are put in the same partition).
This PR adds this functionality into Phobos.
> Enable partition keys to be separate from payload keys

- lib/phobos/cli/start.rb
Issue was introduced by switching `constantize` in for `Object.const_defined?`. This only looks at the top level and doesn't try to load namespaces.
> #98: Fix crash on startup with namespaced handlers

- .rspec
- README.md
- config/phobos.yml.example
- lib/phobos.rb
- lib/phobos/producer.rb
- spec/changelog_spec.rb
- spec/lib/phobos/producer_spec.rb
In investigating the speed of our producers sending synchronously, the `shutdown` and producer creation calls turned out to have increased our Kafka connection time by around 30%. I tried this in a monkey patch and our speed increased by that amount.
This adds a new setting, `cache_sync_producer`, which makes sync producers act like async ones. It requires a `sync_producer_shutdown` call, but also caches the sync producer between calls, so it just reuses the same one and isn't constantly shutting it down and creating new ones.
> Allow sync producers to be cached between calls.

- CHANGELOG.md
- config/phobos.yml.example
- lib/phobos/actions/process_batch.rb
- lib/phobos/listener.rb
- spec/lib/phobos/actions/process_batch_spec.rb
- spec/spec_helper.rb
We have run into multiple issues where processing a batch that takes too long causes the consumer to be kicked out of the group. I know this is called out in the sample config, but I don't really see a point in us *not* heartbeating automatically after every message in batch (as opposed to inline_batch) mode. The configured heartbeat interval ensures that we're not sending heartbeats unnecessarily, and it ensures that as long as we can get through individual messages fast enough, we should be good forever.
@klippx we can aim for 1.9 with this, no?
> Trigger heartbeat if necessary after each message in a batch.

- README.md
- lib/phobos/actions/process_batch_inline.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/batch_message.rb
- lib/phobos/producer.rb
- spec/lib/phobos/actions/process_batch_inline_spec.rb
- spec/lib/phobos/actions/process_message_spec.rb
- spec/lib/phobos/producer_spec.rb
- spec/lib/phobos/test/helper_spec.rb
This PR adds support for producing and consuming messages with headers.
When producing a single message, the `publish` method signature is as follows:
```ruby
def publish(topic, payload, key = nil, partition_key = nil, headers = nil)
end
```
The difference between `key` and `partition_key` here is not clear to me and I appreciate that adding yet another positional argument to the method is not ideal, but I think changing this to use keyword arguments would be outside of the scope of this PR. 
The downside of this implementation is that if users want to specify message headers but do not care about `partition_key`, they will still have to call `publish` with all the arguments, using a value of `nil` for the `partition_key` attribute.
When publishing a batch of messages the API works …
> Add support for producing and consuming messages with headers

- README.md
- examples/publishing_messages_without_consumer.rb
- lib/phobos.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/producer.rb
- spec/lib/phobos/executor_spec.rb
- spec/lib/phobos/listener_spec.rb
- spec/lib/phobos/producer_spec.rb
- spec/spec_helper.rb
Hello 👋 
This PR changes the signature of the `publish` and `publish_async` methods to use keyword arguments instead of positional arguments.
Currently those methods accept 5 arguments, which makes it harder to know in which order those arguments should be specified. The use of keyword arguments makes it easier to use Phobos when producing messages.
> Use keyword arguments when publshing messages

- lib/phobos/actions/process_message.rb
- spec/lib/phobos/actions/process_batch_spec.rb
- spec/lib/phobos/actions/process_message_spec.rb
- spec/lib/phobos/test/helper_spec.rb
Right now it checks `around_batch` / `around_payload` to see if it should print a deprecation message. However, these can legitimately be nil. Metadata should never be nil so this is a more accurate approach to see whether to print the message.
> Fix deprecation message when nil payloads are used

- CHANGELOG.md
- README.md
- lib/phobos/actions/process_batch_inline.rb
- lib/phobos/actions/process_message.rb
- lib/phobos/producer.rb
- spec/lib/phobos/actions/process_batch_inline_spec.rb
- spec/lib/phobos/actions/process_message_spec.rb
- spec/lib/phobos/producer_spec.rb
- spec/lib/phobos/test/helper_spec.rb
@klippx @cassiomarques here it is! Let me know what you think!
I'll create a 1.9.x branch off master before merging this so we can support existing versions long-term.
To clarify, this removes the following patterns:
* `before_consume` method
* `around_consume` as a class method or without yielding values
* `publish` and `async_publish` with positional arguments
We have instead standardized on `around_consume` as an instance method that then yields the values to the `consume` method - so we don't force mutations and have both methods be instance methods.
We also moved to keyword arguments for publishing since the publish methods now have more than the recommended number of arguments and are becoming difficult to use.
> Version 2.0 - Remove deprecated behavior

- CHANGELOG.md
- lib/phobos/actions/process_batch.rb
- lib/phobos/log.rb
- spec/lib/phobos/actions/process_batch_spec.rb
#152 Heartbeat error is manifested into Processing error even though it's not a ProcessingError.
This catches heartbeat error and logs a warning message.
I think phobos cannot take any action based on this heartbeat response. It happens at consumer level in ruby-kafka so it's best to log as a warning instead of an error indicating that something happened.
> process_batch action catches runtime error on heartbeat

- lib/phobos/listener.rb
- spec/lib/phobos/listener_spec.rb
We are seeing issues where a crash on business logic within a consumer causes that listener thread to crash and never come back. This seems to be because the error gets propagated all the way down to RubyKafka, which raises a ProcessingError, which is then *caught* by Phobos and swallowed. The listener is shut down and doesn't come back.
This PR re-raises the exception so that the executor can call `handle_crashed_listener`.
> Raise exception so that executor restarts the thread
